steps:        
  ### build the final image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: 
      - '-c'
      - |
        docker build . -t gcr.io/$PROJECT_ID/eos-build-cache:new -f Dockerfile.eos-build-cache --build-arg EOS_VERSION=$_EOS_VERSION --build-arg JOBS=2
        docker tag gcr.io/$PROJECT_ID/eos-build-cache:new gcr.io/$PROJECT_ID/eos-build-cache
        docker build . -t gcr.io/$PROJECT_ID/eos -t gcr.io/$PROJECT_ID/eos:$_EOS_VERSION -f Dockerfile --build-arg CONTRACTS_VERSION=$_CONTRACTS_VERSION

substitutions: 
  _EOS_VERSION: v1.5.2
  _CONTRACTS_VERSION: v1.5.1

timeout: 7200s

options:
  machineType: 'N1_HIGHCPU_8'
  
images:
  - 'gcr.io/$PROJECT_ID/eos-build-cache'
  - 'gcr.io/$PROJECT_ID/eos'
  - 'gcr.io/$PROJECT_ID/eos:${_EOS_VERSION}'
